# Generated by Django 2.2.2 on 2019-08-03 12:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='itemType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=5, verbose_name='试题类型名称')),
            ],
        ),
        migrations.CreateModel(
            name='paperTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='试卷模板名称')),
                ('date', models.DateTimeField(verbose_name='制卷时间')),
                ('typeOneCount', models.PositiveSmallIntegerField(default=40, verbose_name='单项选择题数量')),
                ('typeOneScore', models.DecimalField(decimal_places=1, default=1, max_digits=3, verbose_name='单项选择题分值')),
                ('typeTwoCount', models.PositiveSmallIntegerField(default=3, verbose_name='基本操作题数量')),
                ('typeTwoScore', models.DecimalField(decimal_places=1, default=5, max_digits=3, verbose_name='基本操作题每题分值')),
                ('typeThreeCount', models.PositiveSmallIntegerField(default=2, verbose_name='简单应用题数量')),
                ('typeThreeScore', models.DecimalField(decimal_places=1, default=12.5, max_digits=3, verbose_name='简单应用题每题分值')),
                ('typeFourCount', models.PositiveSmallIntegerField(default=1, verbose_name='综合应用题数量')),
                ('typeFourScore', models.DecimalField(decimal_places=1, default=20, max_digits=3, verbose_name='综合应用题每题分值')),
            ],
        ),
        migrations.CreateModel(
            name='testItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=200, verbose_name='试题题干')),
                ('options', models.CharField(blank=True, max_length=500, null=True, verbose_name='试题选项')),
                ('picture', models.ImageField(blank=True, null=True, upload_to='', verbose_name='试题图片')),
                ('answer', models.CharField(max_length=1000, verbose_name='参考答案')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ItemPool.itemType')),
            ],
        ),
        migrations.CreateModel(
            name='paperContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='试卷名称')),
                ('content', models.CharField(max_length=100, verbose_name='试卷内容')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ItemPool.paperTemplate')),
            ],
        ),
    ]
