# Generated by Django 2.2.2 on 2019-08-03 14:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ItemPool', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='papercontent',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ItemPool.paperTemplate', verbose_name='试卷模板'),
        ),
        migrations.AlterField(
            model_name='testitem',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ItemPool.itemType', verbose_name='试题类型'),
        ),
    ]
