# Generated by Django 2.2.2 on 2019-08-03 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ItemPool', '0002_auto_20190803_2220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemtype',
            name='name',
            field=models.CharField(max_length=10, verbose_name='试题类型名称'),
        ),
    ]
