# Generated by Django 2.2.2 on 2019-08-04 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ItemPool', '0006_auto_20190803_2336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='papercontent',
            name='content',
            field=models.CharField(max_length=300, verbose_name='试卷内容'),
        ),
    ]
