# Generated by Django 2.2.2 on 2019-08-04 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ItemPool', '0007_auto_20190804_2250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='papercontent',
            name='content',
            field=models.TextField(max_length=400, verbose_name='试卷内容'),
        ),
        migrations.AlterField(
            model_name='testitem',
            name='answer',
            field=models.TextField(max_length=1000, verbose_name='参考答案'),
        ),
        migrations.AlterField(
            model_name='testitem',
            name='options',
            field=models.TextField(blank=True, max_length=600, null=True, verbose_name='试题选项'),
        ),
        migrations.AlterField(
            model_name='testitem',
            name='question',
            field=models.TextField(max_length=200, verbose_name='试题题干'),
        ),
    ]
