# Generated by Django 2.2.2 on 2019-08-04 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ItemPool', '0008_auto_20190804_2257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testitem',
            name='question',
            field=models.TextField(max_length=600, verbose_name='试题题干'),
        ),
    ]
